spring.application.name=dineFlow

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/dineflow
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true